using System.Collections.Generic;

namespace ObraDinnArchipelago.Archipelago;

internal class APData
{
    public enum APItem
    {
        mate2,
        mate4,
        bosun,
        bosunmate,
        surgeon,
        surgeonmate,
        carp,
        carpmate,
        cook,
        butcher,
        gunner,
        gunnermate,
        purser,
        sea9,
        pass5,
        pass1,
        pass2,
        pass3,
        pass4,
        pass6,
        pass7,
        pass8,
        pass9,
        stewship,
        stewm1,
        stewm2,
        stewm3,
        stewm4,
        mid1,
        mid2,
        mid3,
        top5,
        top6,
        top1,
        top4,
        top7,
        top8,
        top9,
        top3,
        top2,
        sea1,
        sea5,
        sea2,
        sea3,
        sea6,
        sea4,
        sea7,
        sea8,
        seac,
        seaa,
        sead,
        seae,
        seaf,
        seag,
    }

    public static readonly Dictionary<string, APItem> CrewIdToItem = new()
    {
        { "mate2", APItem.mate2 },
        { "mate4", APItem.mate4 },
        { "bosun", APItem.bosun },
        { "bosunmate", APItem.bosunmate },
        { "surgeon", APItem.surgeon },
        { "surgeonmate", APItem.surgeonmate },
        { "carp", APItem.carp },
        { "carpmate", APItem.carpmate },
        { "cook", APItem.cook },
        { "butcher", APItem.butcher },
        { "gunner", APItem.gunner },
        { "gunnermate", APItem.gunnermate },
        { "purser", APItem.purser },
        { "sea9", APItem.sea9 },
        { "pass5", APItem.pass5 },
        { "pass1", APItem.pass1 },
        { "pass2", APItem.pass2 },
        { "pass3", APItem.pass3 },
        { "pass4", APItem.pass4 },
        { "pass6", APItem.pass6 },
        { "pass7", APItem.pass7 },
        { "pass8", APItem.pass8 },
        { "pass9", APItem.pass9 },
        { "stewship", APItem.stewship },
        { "stewm1", APItem.stewm1 },
        { "stewm2", APItem.stewm2 },
        { "stewm3", APItem.stewm3 },
        { "stewm4", APItem.stewm4 },
        { "mid1", APItem.mid1 },
        { "mid2", APItem.mid2 },
        { "mid3", APItem.mid3 },
        { "top5", APItem.top5 },
        { "top6", APItem.top6 },
        { "top1", APItem.top1 },
        { "top4", APItem.top4 },
        { "top7", APItem.top7 },
        { "top8", APItem.top8 },
        { "top9", APItem.top9 },
        { "top3", APItem.top3 },
        { "top2", APItem.top2 },
        { "sea1", APItem.sea1 },
        { "sea5", APItem.sea5 },
        { "sea2", APItem.sea2 },
        { "sea3", APItem.sea3 },
        { "sea6", APItem.sea6 },
        { "sea4", APItem.sea4 },
        { "sea7", APItem.sea7 },
        { "sea8", APItem.sea8 },
        { "seac", APItem.seac },
        { "seaa", APItem.seaa },
        { "sead", APItem.sead },
        { "seae", APItem.seae },
        { "seaf", APItem.seaf },
        { "seag", APItem.seag },
    }; 
    
    public static readonly List<string> ChecksList =
    [
        "3 Fates Solved (First Reward)",
        "3 Fates Solved (Second Reward)",
        "3 Fates Solved (Third Reward)",
        "6 Fates Solved (First Reward)",
        "6 Fates Solved (Second Reward)",
        "6 Fates Solved (Third Reward)",
        "9 Fates Solved (First Reward)",
        "9 Fates Solved (Second Reward)",
        "9 Fates Solved (Third Reward)",
        "12 Fates Solved (First Reward)",
        "12 Fates Solved (Second Reward)",
        "12 Fates Solved (Third Reward)",
        "15 Fates Solved (First Reward)",
        "15 Fates Solved (Second Reward)",
        "15 Fates Solved (Third Reward)",
        "18 Fates Solved (First Reward)",
        "18 Fates Solved (Second Reward)",
        "18 Fates Solved (Third Reward)",
        "21 Fates Solved (First Reward)",
        "21 Fates Solved (Second Reward)",
        "21 Fates Solved (Third Reward)",
        "24 Fates Solved (First Reward)",
        "24 Fates Solved (Second Reward)",
        "24 Fates Solved (Third Reward)",
        "27 Fates Solved (First Reward)",
        "27 Fates Solved (Second Reward)",
        "27 Fates Solved (Third Reward)",
        "30 Fates Solved (First Reward)",
        "30 Fates Solved (Second Reward)",
        "30 Fates Solved (Third Reward)",
        "33 Fates Solved (First Reward)",
        "33 Fates Solved (Second Reward)",
        "33 Fates Solved (Third Reward)",
        "36 Fates Solved (First Reward)",
        "36 Fates Solved (Second Reward)",
        "36 Fates Solved (Third Reward)",
        "39 Fates Solved (First Reward)",
        "39 Fates Solved (Second Reward)",
        "39 Fates Solved (Third Reward)",
        "42 Fates Solved (First Reward)",
        "42 Fates Solved (Second Reward)",
        "42 Fates Solved (Third Reward)",
        "45 Fates Solved (First Reward)",
        "45 Fates Solved (Second Reward)",
        "45 Fates Solved (Third Reward)",
        "48 Fates Solved (First Reward)",
        "48 Fates Solved (Second Reward)",
        "48 Fates Solved (Third Reward)",
        "51 Fates Solved (First Reward)",
        "51 Fates Solved (Second Reward)",
        "51 Fates Solved (Third Reward)",
        "54 Fates Solved (First Reward)",
        "54 Fates Solved (Second Reward)",
        "54 Fates Solved (Third Reward)"
    ];
}